### ISSUE TITLE
module_not_found

### ISSUE THREAD

**Issue by lokt02** [va1et/Big_PP2#1]
попытался установить и использовать ваш проект, а он не запускается. Все зависимости установлены, а документации к вашему пакету нет.
![2021-04-05_17-43-11](https://user-images.githubusercontent.com/60607862/113590648-93181d00-963b-11eb-97bf-9ea98b04f0b4.png)

**Comment by va1et** [comment]
Конечно он не работает.Все новые изменения храню у себя, так безопасней и защита от плагиата. GL

**Comment by lokt02** [comment]
Ну как((((((? А если я хочу им воспользоваться то что мне делать? Почините иначе я сплагиачу ваш проект (((())()((((
